services:
  - type: web
    name: foxampy
    runtime: static
    plan: free
    
    # Директория со статическими файлами
    staticPublishPath: ./dist
    
    # Build команда
    buildCommand: npm install && npm run convert-pixels && npm run build
    
    # Переменные окружения
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    
    # Автодеплой
    autoDeploy: true
    
    # Роуты (все пути ведут на index.html для SPA)
    routes:
      - type: rewrite
        source: /_next/static/*
        destination: /_next/static/*
      - type: rewrite
        source: /data/*
        destination: /data/*
      - type: rewrite
        source: /photo/*
        destination: /photo/*
      - type: rewrite
        source: /video/*
        destination: /video/*
      - type: rewrite
        source: /fation/*
        destination: /fation/*
      - type: rewrite
        source: /architecture/*
        destination: /architecture/*
      - type: rewrite
        source: /*
        destination: /index.html
